title: Geo-Wageningen
description: Documentatie Geo-Wageningen
theme: just-the-docs

url: https://pascaldus.github.io/Wageningen

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
